import "./globals.css";
import { Toaster } from "react-hot-toast";
import dynamic from "next/dynamic";
import LenisScrollWrapper from "@/components/LenisScrollWrapper";

const Header = dynamic(() => import("@/components/Header"));
const Footer = dynamic(() => import("@/components/footer/Footer"));

export const metadata = {
  title: "Wappr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Toaster position="top-right" />
        <LenisScrollWrapper>
          <Header />
          {children}
          <Footer />
        </LenisScrollWrapper>
      </body>
    </html>
  );
}
